using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class GameData
{
    //This script defines the variables to be saved

    //Using a long variable to store a serialised dateTime object
    public long lastUpdated;

    //public int jumpCount;
    //public Vector3 playerPosition;

    //Uncomment if using multiple characters/skins
    //public int currentCharacter;

    public string currentSceneName;


    /*This is a dictionary to save the data of collected items, e.g. coins
    The key for the dictionary is a string which represents the unique ID of each collectable, e.g. each coin has a unique ID string
    The boolean shows whether a particular collectable has been collected, e.g. the first two coins of a level but not the last three
    If this is going to be used, make sure the collectable (e.g. coin) has a script with a serialized field to put the unique ID string into. 
    The unique IDs are automatically generated by using guids - refer to this link to do this: https://youtu.be/aUi9aijvpgs?t=1100 */
    //public SerializableDictionary<string, bool> coinsCollected;
    

    // the values defined in the constructor below will be the default values
    //The game starts when there is no data to load
    public GameData()
    {
        //playerPosition = Vector3.zero;

        //Example of using collectable coins
        //coinsCollected = new SerializableDictionary<string, bool>();

        //Uncomment if using multiple characters/skins
        //currentCharacter = 0;
        currentSceneName = "";
    }
}

